### ISSUE TITLE
Improve plugin installation

### ISSUE THREAD

**Issue by wjt** [flathub/io.github.endless_sky.endless_sky#22]
According to https://github.com/endless-sky/endless-sky/wiki/CreatingPlugins, Endless Sky can load plugins from `/usr/share/games/endless-sky/plugins` and from `~/.local/share/endless-sky/plugins`.

In Flatpak-land, of course those paths are different. It would be nice for someone involved in this game to update that wiki page.

For per-user plugins, the correct directory is `~/.var/app/io.github.endless_sky.endless_sky/data/endless-sky/plugins`.

For system-wide plugins… I was about to say, there should be an extension point mounted at `/app/share/games/endless-sky/plugins` so that plugins could be shipped as Flatpak extensions. However that is likely to be complicated by the `endless-sky-high-dpi` plugin already being installed there.

**Comment by quyykk** [comment]
> I was about to say, there should be an extension point mounted at /app/share/games/endless-sky/plugins so that plugins could be shipped as Flatpak extensions

I didn't know that was a thing lol. That's definitely a good idea! The high dpi plugin shouldn't be shipped by default anyways, because it increases VRAM consumption by a lot.

Starting with 0.10.0 there's an "Open Plugins" button in the plugins page too, but yeah I can update that wiki page.

**Comment by wjt** [comment]
> Starting with 0.10.0

#21? ;)
