### ISSUE TITLE
More Flathub page claims the game is proprietary and not open source 

### ISSUE THREAD

**Issue by MCOfficer** [flathub/io.github.endless_sky.endless_sky#28]
*copied from https://github.com/endless-sky/endless-sky/issues/9312*

---

### Location

https://flathub.org/apps/io.github.endless_sky.endless_sky

### Describe the issue

The Flathub page for the game claims it's a proprietary game, even though it's open-source.

![Screenshot showing the game tagged as proprietary](https://github.com/endless-sky/endless-sky/assets/16920817/84fddba8-93b9-476f-bcd7-ae738c1cbe52)

### Expected content

It should be tagged as an open-source game with a GPL-3 license.

**Comment by quyykk** [comment]
The reason is the CC license we use for images, but the assets licenses shouldn't be specified in the xml file for Flathub. Incidentally, that was fixed a while ago so this will be fixed in future versions.
