### ISSUE TITLE
Allowing saves from home directory does not work

### ISSUE THREAD

**Issue by arteymix** [flathub/io.github.endless_sky.endless_sky#38]
I'm trying to add the `--filesystem=~/.local/share/endless-sky/saves` so that Endless Sky can load saves from my home directory, but it does not work.

**Comment by quyykk** [comment]
The game uses the internal user directory from Flatpak, so it never sees your user folder. You will need to pass a flag to the application as well. Like this:

```bash
$ flatpak run --filesystem=~/.local/share/endless-sky io.github.endless_sky.endless_sky --config ~/.local/share/endless-sky
```

**Comment by arteymix** [comment]
Ok, it's working.

Is it possible to change the build to make it default to `~/.local/share/endless-sky` for user preferences and saves?

**Comment by quyykk** [comment]
No, flatpak doesn't recommend doing this by default. However, you can use this shorter command:

```bash
$ flatpak run --filesystem=xdg-data/endless-sky io.github.endless_sky.endless_sky
```

And you can use flatpak overrides to make it permanent on your system like this:

```bash
$ flatpak override --filesystem=xdg-data/endless-sky io.github.endless_sky.endless_sky
```

**Comment by arteymix** [comment]
Ok, I've set that in Flatseal:

![image](https://github.com/flathub/io.github.endless_sky.endless_sky/assets/1318477/12e8937e-41d1-4aae-83c7-093c1c4c70a6)

and it works great!
